# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: security_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'security_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16security_service.proto\x12\x0e\x61\x65gis.security\"&\n\x0eInspectRequest\x12\x14\n\x0crequest_body\x18\x01 \x01(\t\"3\n\x0fInspectResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2d\n\x0fSecurityService\x12Q\n\x0eInspectPayload\x12\x1e.aegis.security.InspectRequest\x1a\x1f.aegis.security.InspectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSPECTREQUEST']._serialized_start=42
  _globals['_INSPECTREQUEST']._serialized_end=80
  _globals['_INSPECTRESPONSE']._serialized_start=82
  _globals['_INSPECTRESPONSE']._serialized_end=133
  _globals['_SECURITYSERVICE']._serialized_start=135
  _globals['_SECURITYSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
